name = "kfh"
compatibility_date = "2025-05-25"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist/"
not_found_handling = "404-page"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"
