import { commonKeys, numKey } from "./_common.js";

const cw01 = {
  'a': commonKeys.frac,
  'b': commonKeys.eq,
  'c': commonKeys.log,
  'd': commonKeys.square,
  'e': ['(e)'],
// 'f': [''],
  'g': commonKeys.log_,
  'h': ['(ln)'],
  'i': commonKeys.logab,
  'j': commonKeys.sin,
  'k': commonKeys.cos,
  'l': commonKeys.tan,
  'm': ['(;)'],
  'n': ['[FORMAT]'],
  'o': ['[DEL]', '[⌫]'],
  'p': commonKeys.minus,
  'q': ['[SHIFT]', '[SECONDE]'],
  'r': ['[格式]'],
  's': commonKeys.sqrt,
  't': commonKeys.neg,
  'u': ['[π]', '[Pi]'],
  'v': ['(log(a,b))', '(logab)', '(log(■,□))'],
  'w': ['[HOME]', '[主屏幕]', '[ACCUEIL]'],
  'x': ['(\'\'")', '(DMS)', '(°\'")'],
  'y': ['(Integral)', '(∫)'],
  'z': ['((-))'],
  'A': ['(a(b/c))', '(a b/c)', '(■(□/□))'],
  'B': commonKeys.exe,
  'C': commonKeys.ac,
  'D': ['(Rec)'],
  'E': commonKeys.up,
  'F': commonKeys.nsqrt,
  'G': ['(nPr)'],
  'H': ['(nCr)'],
  'I': ['[TOOLS]', '[工具]', '[OUTILS]'],
  'J': ['[QR]'],
  'K': ['[*10^x]', '[×10^x]', '[×10^■]'],
  'L': ['[SETTINGS]', '[设置]', '[CONFIG]'],
  'M': commonKeys.ans,
// 'N': [''],
  'O': commonKeys.multi,
  'P': commonKeys.division,
  'Q': ['[FUNCTION]', '[f(x)]', '[函数]', '[功能]', '[FONCTION]'],
  'R': commonKeys.down,
  'S': ['(Pol)'],
  'T': ['[CATALOG]', '[目录]'],
  'U': commonKeys.i,
  'V': ['(z)'],
  'W': ['[ON]', '[开机]'],
  'X': ['(x)'],
  'Y': commonKeys.ddx,
  'Z': commonKeys.arg,
  '!': commonKeys.left,
  '$': commonKeys.right,
  '"': commonKeys.approx,
  '\'': ['[VARIABLE]', '[变量]'],
  '%': ['[PAGEUP]', '[PageUp]', '[↟上翻]', '[上翻]'],
  '&': ['[PAGEDOWN]', '[PageDown]', '[↡下翻]', '[下翻]'],
  '(': commonKeys.open,
  ')': commonKeys.close,
  '*': ['(Ans)'],
  '+': commonKeys.plus,
  '.': commonKeys.dot,
  ',': commonKeys.comma,
  '-': commonKeys.divisionr,
  '/': commonKeys.reciprocal,
  '=': ['(=)'],
  '^': ['[^]', '[■^□]', '[x^■]'],
  '~': ['(Simp)'],
  '#': commonKeys.comma_,
  '{': commonKeys.pi,
  '<': commonKeys.sin1,
  '>': commonKeys.cos1,
  '?': commonKeys.tan1,
  '@': ['(y)'],
  '[': ['[x]'],
  '}': ['(PreAns)'],
  ']': commonKeys.rec,
  ':': commonKeys.rec_,
  ';': commonKeys.rec__,
// '_': [''],
  '`': ['[BACK]', '[返回]'],
  '|': ['[OK]'],
// '\\': [''],
};

numKey(cw01);

export { cw01 };
