import {
  b_adc,
  b_approx,
  b_arg,
  b_comma,
  b_cos1,
  b_ddx,
  b_i,
  b_log,
  b_nsqrt,
  b_pi,
  b_rec,
  b_rec_,
  b_rec__,
  b_reciprocal_cw,
  b_sin1,
  b_tan1,
  k_ac,
  k_ans,
  k_close,
  k_comma_,
  k_cos,
  k_division,
  k_dot,
  k_down,
  k_eq,
  k_exe,
  k_frac,
  k_left,
  k_log_,
  k_logab,
  k_minus,
  k_multi,
  k_neg,
  k_open,
  k_pi,
  k_plus,
  k_power_cw,
  k_right,
  k_sin,
  k_sqrt,
  k_square_cw,
  k_tan,
  k_up,
  numKey,
} from './_common.js';

const cw01 = {
  'a': k_frac,
  'b': k_eq,
  'c': b_log,
  'd': k_square_cw,
  'e': ['(e)'],
  'f': ['[转换]'],
  'g': k_log_,
  'h': ['(ln)'],
  'i': k_logab,
  'j': k_sin,
  'k': k_cos,
  'l': k_tan,
  'm': ['(;)'],
  'n': ['[FORMAT]'],
  'o': ['[⌫]', '[DEL]'],
  'p': k_minus,
  'q': ['[⬆]', '[SHIFT]', '[SECONDE]'],
  'r': ['[格式]'],
  's': k_sqrt,
  't': k_neg,
  'u': k_pi,
  'v': ['(log(■,□))', '(log(a,b))', '(logab)'],
  'w': ['[⌂]', '[HOME]', '[主屏幕]', '[ACCUEIL]', '[START]'],
  'x': ['(°\'")', '(\'\'")', '(DMS)'],
  'y': ['(∫)', '(Integral)'],
  'z': ['((-))'],
  'A': b_adc,
  'B': k_exe,
  'C': k_ac,
  'D': ['(Rec)'],
  'E': k_up,
  'F': b_nsqrt,
  'G': ['(nPr)'],
  'H': ['(nCr)'],
  'I': ['[○○○]', '[TOOLS]', '[工具]', '[OUTILS]', '[OPTIES]'],
  'J': ['[QR]'],
  'K': ['[×10^■]', '[*10^x]', '[×10^x]'],
  'L': ['[SETTINGS]', '[设置]', '[CONFIG]', '[INSTELLING]'],
  'M': k_ans,
  'N': ['(🔄)', '(转换菜单)', '(FORMAT Menu)'],
  'O': k_multi,
  'P': k_division,
  'Q': ['[f(x)]', '[FUNCTION]', '[函数]', '[功能]', '[FONCTION]', '[FUNCTIE]'],
  'R': k_down,
  'S': ['(Pol)'],
  'T': ['[📖]', '[CATALOG]', '[目录]', '[GIDS]'],
  'U': b_i,
  'V': ['(z)'],
  'W': [/*'[⏻]', */'[ON]', '[开机]', '[AAN]'],
  'X': ['(x)'],
  'Y': b_ddx,
  'Z': b_arg,
  '!': k_left,
  '$': k_right,
  '"': b_approx,
  '\'': ['[VARIABLE]', '[变量]', '[VARIABELE]'],
  '%': ['[↟]', '[PAGEUP]', '[PageUp]', '[↟上翻]', '[上翻]'],
  '&': ['[↡]', '[PAGEDOWN]', '[PageDown]', '[↡下翻]', '[下翻]'],
  '(': k_open,
  ')': k_close,
  '*': ['(Ans)'],
  '+': k_plus,
  '.': k_dot,
  ',': b_comma,
  '-': ['(÷R)', '(/R)'],
  '/': b_reciprocal_cw,
  '=': ['(=)'],
  '^': k_power_cw,
  '~': ['(Simp)'],
  '#': k_comma_,
  '{': b_pi,
  '<': b_sin1,
  '>': b_cos1,
  '?': b_tan1,
  '@': ['(y)'],
  '[': ['[x]'],
  '}': ['(PreAns)'],
  ']': b_rec,
  ':': b_rec_,
  ';': b_rec__,
  '_': ['(☰)', '(目录列表)', '(CATALOG List)'],
  '`': ['[BACK]', '[返回]'],
  '|': ['[OK]'],
// '\\': [''],
};

numKey(cw01);

export { cw01 };
