import {
  k_ac,
  k_adc,
  k_ans,
  k_approx,
  k_arg,
  k_close,
  k_comma,
  k_comma_,
  k_cos,
  k_cos1,
  k_ddx,
  k_division,
  k_dot,
  k_down,
  k_eq,
  k_exe,
  k_frac,
  k_i,
  k_left,
  k_log,
  k_log_,
  k_logab,
  k_minus,
  k_multi,
  k_neg,
  k_nsqrt,
  k_open,
  k_pi,
  k_pi_,
  k_plus,
  k_power,
  k_rec,
  k_rec_,
  k_rec__,
  k_reciprocal,
  k_right,
  k_sin,
  k_sin1,
  k_sqrt,
  k_square,
  k_tan,
  k_tan1,
  k_up,
  numKey
} from "./_common.js";

const cw01 = {
  'a': k_frac,
  'b': k_eq,
  'c': k_log,
  'd': k_square,
  'e': ['(e)'],
// 'f': [''],
  'g': k_log_,
  'h': ['(ln)'],
  'i': k_logab,
  'j': k_sin,
  'k': k_cos,
  'l': k_tan,
  'm': ['(;)'],
  'n': ['[FORMAT]'],
  'o': ['[DEL]', '[⌫]'],
  'p': k_minus,
  'q': ['[SHIFT]', '[SECONDE]'],
  'r': ['[格式]'],
  's': k_sqrt,
  't': k_neg,
  'u': k_pi_,
  'v': ['(log(a,b))', '(logab)', '(log(■,□))'],
  'w': ['[HOME]', '[主屏幕]', '[ACCUEIL]'],
  'x': ['(\'\'")', '(DMS)', '(°\'")'],
  'y': ['(Integral)', '(∫)'],
  'z': ['((-))'],
  'A': k_adc,
  'B': k_exe,
  'C': k_ac,
  'D': ['(Rec)'],
  'E': k_up,
  'F': k_nsqrt,
  'G': ['(nPr)'],
  'H': ['(nCr)'],
  'I': ['[TOOLS]', '[工具]', '[OUTILS]'],
  'J': ['[QR]'],
  'K': ['[*10^x]', '[×10^x]', '[×10^■]'],
  'L': ['[SETTINGS]', '[设置]', '[CONFIG]'],
  'M': k_ans,
// 'N': [''],
  'O': k_multi,
  'P': k_division,
  'Q': ['[FUNCTION]', '[f(x)]', '[函数]', '[功能]', '[FONCTION]'],
  'R': k_down,
  'S': ['(Pol)'],
  'T': ['[CATALOG]', '[目录]'],
  'U': k_i,
  'V': ['(z)'],
  'W': ['[ON]', '[开机]'],
  'X': ['(x)'],
  'Y': k_ddx,
  'Z': k_arg,
  '!': k_left,
  '$': k_right,
  '"': k_approx,
  '\'': ['[VARIABLE]', '[变量]'],
  '%': ['[PAGEUP]', '[PageUp]', '[↟上翻]', '[上翻]'],
  '&': ['[PAGEDOWN]', '[PageDown]', '[↡下翻]', '[下翻]'],
  '(': k_open,
  ')': k_close,
  '*': ['(Ans)'],
  '+': k_plus,
  '.': k_dot,
  ',': k_comma,
  '-': ['(÷R)', '(/R)'],
  '/': k_reciprocal,
  '=': ['(=)'],
  '^': k_power,
  '~': ['(Simp)'],
  '#': k_comma_,
  '{': k_pi,
  '<': k_sin1,
  '>': k_cos1,
  '?': k_tan1,
  '@': ['(y)'],
  '[': ['[x]'],
  '}': ['(PreAns)'],
  ']': k_rec,
  ':': k_rec_,
  ';': k_rec__,
// '_': [''],
  '`': ['[BACK]', '[返回]'],
  '|': ['[OK]'],
// '\\': [''],
};

numKey(cw01);

export { cw01 };
