import {
  k_ac,
  k_ans,
  k_approx,
  k_arg,
  k_close,
  k_comma,
  k_comma_,
  k_cos,
  k_cos1,
  k_ddx,
  k_division,
  k_divisionr,
  k_dot,
  k_down,
  k_eng,
  k_eq,
  k_exe,
  k_frac,
  k_i,
  k_left,
  k_log,
  k_log_,
  k_logab,
  k_minus,
  k_multi,
  k_neg,
  k_nsqrt,
  k_open,
  k_pi,
  k_plus,
  k_rec,
  k_rec_,
  k_rec__,
  k_reciprocal,
  k_right,
  k_sin,
  k_sin1,
  k_sqrt,
  k_square,
  k_tan,
  k_tan1,
  k_up,
  numKey
} from "./_common.js";

const cwex = {
  'a': k_frac,
  'b': k_eng,
  'c': k_log,
  'd': k_square,
  'e': ['[Abs]'],
  'f': ['(Abs)'],
  'g': k_log_,
  'h': ['[ln]'],
  'i': k_logab,
  'j': k_sin,
  'k': k_cos,
  'l': k_tan,
  'm': ['[M+]'],
  'n': ['[S<>D]', '[S⇔D]', '[SD]', '[S<=>D]'],
  'o': ['[DEL]'],
  'p': k_minus,
  'q': ['[SHIFT]'],
  'r': ['[CALC]'],
  's': k_sqrt,
  't': ['[菜单]'],
  'u': ['[x⁻¹]', '[x^-1]'],
  'v': ['[%]'],
  'w': ['[MENU]'],
  'x': ['[\'\'"]', '[DMS]', '[°\'"]'],
  'y': ['[Integral]', '[∫]'],
  'z': k_neg,
  'A': ['(ad/c)', '(a d/c)', '(■(□/□))'],
  'B': k_exe,
  'C': k_ac,
  'D': ['[x^3]', '[x³]'],
  'E': k_up,
  'F': k_nsqrt,
  'G': ['(10^x)', '(10^■)'],
  'H': ['(e^x)', '(e^■)'],
  'I': ['(Σ)', '(Sigma)'],
  'J': ['[STO]'],
  'K': ['[*10^x]', '[×10^x]'],
  'L': ['(SETUP)'],
  'M': k_ans,
  'N': ['(a(b/c)⇔d/c)', '(a(b/c)<>d/c)', '(a(b/c)<=>d/c)', '(a b/c⇔d/c)', '(a b/c<>d/c)', '(a b/c<=>d/c)'],
  'O': k_multi,
  'P': k_division,
  'Q': ['[ALPHA]'],
  'R': k_down,
  'S': ['(³√(■))', '(3rd Root)', '(3 sqrt a)'],
  'T': ['[OPTN]'],
  'U': k_i,
  'V': ['(M-)'],
  'W': ['[ON]'],
  'X': ['(Left)', '(←)'],
  'Y': k_ddx,
  'Z': k_arg,
  '!': k_left,
  '$': k_right,
  '"': k_approx,
  '\'': ['(x^3)', '(x³)'],
  '%': ['[x!]'],
  '&': ['(%)'],
  '(': k_open,
  ')': k_close,
  '*': ['[Σ]', '[Sigma]'],
  '+': k_plus,
  '.': k_dot,
  ',': k_comma,
  '-': k_divisionr,
  '/': k_reciprocal,
  '=': k_eq,
  '^': ['[^]', '[x^■]'],
  '~': ['[Simp]'],
  '#': k_comma_,
  '{': k_pi,
  '<': k_sin1,
  '>': k_cos1,
  '?': k_tan1,
  '@': ['[y]'],
  '[': ['[x]'],
  '}': ['[Π]', '[Product]'],
  ']': k_rec,
  ':': k_rec_,
  ';': k_rec__,
  '_': ['[sen]'],
  '`': ['[|__]', '[∟]', '[⌙]'],
  '|': ['[开机]'],
  // '\\': [''],
};

numKey(cwex);

export { cwex };
