import { commonKeys, numKey } from "./_common.js";

const cwex = {
  'a': commonKeys.frac,
  'b': commonKeys.eng,
  'c': commonKeys.log,
  'd': commonKeys.square,
  'e': ['[Abs]'],
  'f': ['(Abs)'],
  'g': commonKeys.log_,
  'h': ['[ln]'],
  'i': commonKeys.logab,
  'j': commonKeys.sin,
  'k': commonKeys.cos,
  'l': commonKeys.tan,
  'm': ['[M+]'],
  'n': ['[S<>D]', '[S⇔D]', '[SD]', '[S<=>D]'],
  'o': ['[DEL]'],
  'p': commonKeys.minus,
  'q': ['[SHIFT]'],
  'r': ['[CALC]'],
  's': commonKeys.sqrt,
  't': ['[菜单]'],
  'u': ['[x⁻¹]', '[x^-1]'],
  'v': ['[%]'],
  'w': ['[MENU]'],
  'x': ['[\'\'"]', '[DMS]', '[°\'"]'],
  'y': ['[Integral]', '[∫]'],
  'z': commonKeys.neg,
  'A': ['(ad/c)', '(a d/c)', '(■(□/□))'],
  'B': commonKeys.exe,
  'C': commonKeys.ac,
  'D': ['[x^3]', '[x³]'],
  'E': commonKeys.up,
  'F': commonKeys.nsqrt,
  'G': ['(10^x)', '(10^■)'],
  'H': ['(e^x)', '(e^■)'],
  'I': ['(Σ)', '(Sigma)'],
  'J': ['[STO]'],
  'K': ['[*10^x]', '[×10^x]'],
  'L': ['(SETUP)'],
  'M': commonKeys.ans,
  'N': ['(a(b/c)⇔d/c)', '(a(b/c)<>d/c)', '(a(b/c)<=>d/c)', '(a b/c⇔d/c)', '(a b/c<>d/c)', '(a b/c<=>d/c)'],
  'O': commonKeys.multi,
  'P': commonKeys.division,
  'Q': ['[ALPHA]'],
  'R': commonKeys.down,
  'S': ['(³√(■))', '(3rd Root)', '(3 sqrt a)'],
  'T': ['[OPTN]'],
  'U': commonKeys.i,
  'V': ['(M-)'],
  'W': ['[ON]'],
  'X': ['(Left)', '(←)'],
  'Y': commonKeys.ddx,
  'Z': commonKeys.arg,
  '!': commonKeys.left,
  '$': commonKeys.right,
  '"': commonKeys.approx,
  '\'': ['(x^3)', '(x³)'],
  '%': ['[x!]'],
  '&': ['(%)'],
  '(': commonKeys.open,
  ')': commonKeys.close,
  '*': ['[Σ]', '[Sigma]'],
  '+': commonKeys.plus,
  '.': commonKeys.dot,
  ',': commonKeys.comma,
  '-': commonKeys.divisionr,
  '/': commonKeys.reciprocal,
  '=': commonKeys.eq,
  '^': ['[^]', '[x^■]'],
  '~': ['[Simp]'],
  '#': commonKeys.comma_,
  '{': commonKeys.pi,
  '<': commonKeys.sin1,
  '>': commonKeys.cos1,
  '?': commonKeys.tan1,
  '@': ['[y]'],
  '[': ['[x]'],
  '}': ['[Π]', '[Product]'],
  ']': commonKeys.rec,
  ':': commonKeys.rec_,
  ';': commonKeys.rec__,
  '_': ['[sen]'],
  '`': ['[|__]', '[∟]', '[⌙]'],
  '|': ['[开机]'],
  // '\\': [''],
};

numKey(cwex);

export { cwex };
