import { commonKeys, numKey } from "./_common.js";

const es03 = {
  'a': commonKeys.frac,
  'b': commonKeys.eng,
  'c': ['[hyp]'],
  'd': commonKeys.square,
  'e': ['[Abs]'],
  'f': ['[7-]'],
  'g': commonKeys.log_,
  'h': ['[ln]'],
  'i': commonKeys.logab,
  'j': commonKeys.sin,
  'k': commonKeys.cos,
  'l': commonKeys.tan,
  'm': ['[M+]'],
  'n': ['[S<>D]', '[S⇔D]', '[SD]', '[S<=>D]'],
  'o': ['[DEL]'],
  'p': commonKeys.minus,
  'q': ['[SHIFT]'],
  'r': ['[CALC]'],
  's': commonKeys.sqrt,
  't': commonKeys.rec,
  'u': ['[x⁻¹]', '[x^-1]'],
  'v': ['[%]'],
  'w': ['[MODE]'],
  'x': ['[\'\'"]', '[DMS]', '[°\'"]'],
  'y': ['[Integral]', '[∫]'],
  'z': commonKeys.neg,
  'A': ['(ad/c)', '(a d/c)', '(■(□/□))'],
  'B': ['(DRG)', '(DRG▶)'],
  'C': commonKeys.ac,
  'D': ['[x^3]', '[x³]'],
  'E': commonKeys.up,
  'F': commonKeys.nsqrt,
  'G': ['(10^x)', '(10^■)'],
  'H': ['(e^x)', '(e^■)'],
  'I': ['(Σ)', '(Sigma)'],
  'J': ['[RCL]'],
  'K': ['[*10^x]', '[×10^x]'],
  'L': commonKeys.pi,
  'M': commonKeys.ans,
  'N': ['(a(b/c)⇔d/c)', '(a(b/c)<>d/c)', '(a(b/c)<=>d/c)', '(a b/c⇔d/c)', '(a b/c<>d/c)', '(a b/c<=>d/c)'],
  'O': commonKeys.multi,
  'P': commonKeys.division,
  'Q': ['[ALPHA]'],
  'R': commonKeys.down,
  'S': ['(³√(■))', '(3rd Root)', '(3 sqrt a)'],
  'T': commonKeys.rec__,
  'U': commonKeys.i,
  'V': commonKeys.exe,
  'W': ['[ON]'],
  'X': ['(Left)', '(←)'],
  'Y': commonKeys.ddx,
  'Z': commonKeys.arg,
  '!': commonKeys.left,
  '$': commonKeys.right,
  '"': commonKeys.approx,
  '\'': ['[HIDUP]'],
  '%': ['[x!]'],
  '&': ['(%)'],
  '(': commonKeys.open,
  ')': commonKeys.close,
  '*': commonKeys.rec_,
  '+': commonKeys.plus,
  '.': commonKeys.dot,
  ',': commonKeys.comma,
  '-': commonKeys.divisionr,
  // '/': [''],
  '=': commonKeys.eq,
  '^': ['[^]', '[x^■]'],
  '~': ['[Simp]'],
  '#': ['[|-]', '[├]'],
  '{': ['[EFF]'],
  '<': commonKeys.sin1,
  '>': commonKeys.cos1,
  '?': commonKeys.tan1,
  '@': ['[Y]'],
  '[': ['[X]'],
  '}': ['[Π]', '[Product]'],
  ']': ['(Conv)', '(▶Conv)'],
  ':': ['[Rép]', '[Rep]'],
  ';': ['[SUPPR]'],
  '_': commonKeys.comma_,
  '`': ['[SECONDE]'],
  '|': ['(a*10^x)', '(a×10^x)'],
  // '\\': [''],
};

numKey(es03)

export { es03 };
